{% set name = "multipart" %}
{% set version = "1.2.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/multipart-{{ version }}.tar.gz
  sha256: 829b909b67bc1ad1c6d4488fcdc6391c2847842b08323addf5200db88dbe9480

build:
  skip: true # [py<38]
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python
    - pip
    - setuptools
    - wheel
    - flit-core >=3.9,<4
  run:
    - python

test:
  source_files:
    - test
  imports:
    - multipart
  commands:
    - pip check
    # skip test due to https://github.com/defnull/multipart/issues/37
    - pytest -v -k "not test_urlencoded" test
  requires:
    - pip
    - pytest

about:
  home: https://github.com/defnull/multipart
  summary: Parser for multipart/form-data.#
  description: |
    This module provides a parser for the multipart/form-data format. It can read from a file, a socket or a WSGI environment. The parser can be used to replace cgi.FieldStorage to work around its limitations.
  license: MIT
  license_file: LICENSE
  license_family: MIT
  dev_url: https://github.com/defnull/multipart
  doc_url: https://github.com/defnull/multipart

extra:
  recipe-maintainers:
    - JamesRobertsonGames
